### ISSUE TITLE
Feature Request: Add an arguements field for the LibTerm iOS shortcuts action

### ISSUE THREAD

**Issue by VincentCCandela** [ColdGrub1384/LibTerm#37] opened 2019-11-04 00:22 UTC
In the shortcuts app, the LibTerm action is kind of useful. In order for it to be truly useful, then please add an arguments field for this action. For example, python commands could be run with different input to do different things such as inputting a url from a YouTube video into YouTube-dl so that the video can be downloaded.

**Comment by dullbananas** [comment] 2019-11-04 00:54
Just put the arguments into the command field. If you're talking about stdin, then this is a duplicate of the issue I opened

**Closed** 2019-11-10 03:28 UTC
